#!/usr/bin/env python

import os,sys
topdir = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))

args = sys.argv[1:]
if not args:
  args = ["8000"]
webdir = os.path.join(topdir, "web")
os.chdir(webdir)
os.execvp("python", ["python", "-m", "SimpleHTTPServer"] + args)

